### ISSUE TITLE
Still seeing crashes in v3.4.5

### ISSUE THREAD

**Issue by darwin** [thomthom/cleanup#22]
Might be related to #21

Call to `entities.empty?` on this particular line is problematic:
https://github.com/thomthom/cleanup/blob/3b94238732a52153c18c5aa53bf7147ae951fb36/src/tt_cleanup/core.rb#L921

```
Error: #<NoMethodError: undefined method `empty?' for #<Sketchup::Entities:0x00000002b61f4880>>
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:921:in `erase_duplicate_faces'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:582:in `block in cleanup!'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_Lib2/entities.rb:98:in `each_entities'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_Lib2/entities.rb:107:in `block in each_entities'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_Lib2/entities.rb:101:in `each'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_Lib2/entities.rb:101:in `each_entities'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:749:in `each_entities_in_scope'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:581:in `cleanup!'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:253:in `cleanup_last'
/Users/darwin/Library/Application Support/SketchUp 2023/SketchUp/Plugins/TT_CleanUp/core.rb:234:in `block in <module:CleanUp>'
```

**Comment by thomthom** [comment]
This is now live on Extension Warehouse and SketchUcation.

Sorry for the churn. Did some cleanups and this extension has so many options that it's a challenge to test everything.

**Comment by roboorto2018** [comment]
Grazie, 
It works with the new version you posted. Great
